name: CI

permissions: { }

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: "zizmor"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Run zizmor"
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          advanced-security: false

  typos:
    name: "typos"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Run typos"
        uses: crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14 # v1.48.0

  cargo-fmt:
    name: "cargo fmt"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@nightly # zizmor: ignore[unpinned-uses]
        with:
          components: rustfmt

      - run: cargo fmt-nightly --check

  cargo-clippy:
    name: "cargo clippy"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        if: github.event_name == 'pull_request'
        with:
          lookup-only: false # zizmor: ignore[cache-poisoning]

      - uses: dtolnay/rust-toolchain@nightly # zizmor: ignore[unpinned-uses]
        with:
          components: clippy

      - run: cargo clippy --all-targets

  cargo-build-release:
    name: "cargo build (release) on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        if: github.event_name == 'pull_request'
        with:
          lookup-only: false # zizmor: ignore[cache-poisoning]

      - uses: dtolnay/rust-toolchain@stable # zizmor: ignore[unpinned-uses]

      - if: runner.os == 'Linux'
        uses: wild-linker/action@latest # zizmor: ignore[unpinned-uses]

      - name: "Build"
        run: cargo build --release
